// Mock data for the app
export const mockUsers = [
  {
    id: "1",
    firstName: "Sarah",
    lastName: "Chen",
    age: 28,
    bio: "Yoga enthusiast, bookworm, and aspiring chef. Love hiking and deep conversations over coffee.",
    profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    city: "San Francisco",
    state: "CA",
    interests: ["Yoga", "Cooking", "Hiking", "Reading"],
    values: ["Authenticity", "Growth", "Compassion"],
    matchScore: 92,
    distance: 2.4,
    online: true,
  },
  {
    id: "2",
    firstName: "Marcus",
    lastName: "Johnson",
    age: 34,
    bio: "Music producer by day, community volunteer by night. Believe in building bridges between generations.",
    profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    city: "Oakland",
    state: "CA",
    interests: ["Music", "Volunteering", "Photography", "Basketball"],
    values: ["Community", "Integrity", "Creativity"],
    matchScore: 87,
    distance: 5.1,
    online: false,
  },
  {
    id: "3",
    firstName: "Emma",
    lastName: "Rodriguez",
    age: 26,
    bio: "Plant mom, board game geek, and cat lover. Always looking for new friends to share a meal with.",
    profileImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    city: "San Francisco",
    state: "CA",
    interests: ["Board Games", "Gardening", "Cooking", "Art"],
    values: ["Kindness", "Creativity", "Adventure"],
    matchScore: 85,
    distance: 1.8,
    online: true,
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Park",
    age: 31,
    bio: "Software developer who loves trail running and building things. Looking for genuine friendships.",
    profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    city: "Berkeley",
    state: "CA",
    interests: ["Running", "Tech", "Camping", "Coffee"],
    values: ["Honesty", "Growth", "Balance"],
    matchScore: 81,
    distance: 8.3,
    online: true,
  },
];

export const mockCommunities = [
  {
    id: "1",
    name: "Bay Area Hikers",
    description: "Weekly hikes exploring trails around the Bay Area. All fitness levels welcome!",
    category: "Outdoors",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop",
    memberCount: 234,
    city: "San Francisco",
    distance: 0.5,
  },
  {
    id: "2",
    name: "Foodies United",
    description: "Monthly potlucks, restaurant hopping, and cooking workshops for food lovers.",
    category: "Food & Drink",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
    memberCount: 189,
    city: "Oakland",
    distance: 3.2,
  },
  {
    id: "3",
    name: "Creative Collective",
    description: "A space for artists, writers, and makers to share, collaborate, and inspire.",
    category: "Arts & Culture",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600&h=400&fit=crop",
    memberCount: 156,
    city: "San Francisco",
    distance: 1.1,
  },
  {
    id: "4",
    name: "Mindful Mornings",
    description: "Start your day with meditation, yoga, and meaningful conversations.",
    category: "Wellness",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=400&fit=crop",
    memberCount: 98,
    city: "San Francisco",
    distance: 0.8,
  },
];

export const mockEvents = [
  {
    id: "1",
    name: "Sunset Hike at Lands End",
    date: "Mar 2, 2026",
    time: "5:00 PM",
    location: "Lands End Trail, SF",
    attendees: 24,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&h=400&fit=crop",
    community: "Bay Area Hikers",
  },
  {
    id: "2",
    name: "Korean BBQ Night",
    date: "Mar 5, 2026",
    time: "7:00 PM",
    location: "Gogi Time, Oakland",
    attendees: 16,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    community: "Foodies United",
  },
  {
    id: "3",
    name: "Morning Meditation",
    date: "Mar 8, 2026",
    time: "7:00 AM",
    location: "Golden Gate Park",
    attendees: 12,
    image: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=600&h=400&fit=crop",
    community: "Mindful Mornings",
  },
];

export const mockMessages = [
  {
    id: "1",
    user: mockUsers[0],
    lastMessage: "Hey! Want to check out that new trail this weekend?",
    time: "2m ago",
    unread: 2,
  },
  {
    id: "2",
    user: mockUsers[1],
    lastMessage: "The community meetup was amazing! Thanks for organizing.",
    time: "1h ago",
    unread: 0,
  },
  {
    id: "3",
    user: mockUsers[2],
    lastMessage: "Game night at my place Saturday? 🎲",
    time: "3h ago",
    unread: 1,
  },
  {
    id: "4",
    user: mockUsers[3],
    lastMessage: "Just finished that book you recommended!",
    time: "1d ago",
    unread: 0,
  },
];

export const interestCategories = [
  { name: "Outdoors", emoji: "🌿", interests: ["Hiking", "Camping", "Running", "Cycling", "Surfing"] },
  { name: "Food & Drink", emoji: "🍳", interests: ["Cooking", "Baking", "Coffee", "Wine", "Restaurants"] },
  { name: "Arts & Culture", emoji: "🎨", interests: ["Art", "Music", "Photography", "Writing", "Film"] },
  { name: "Wellness", emoji: "🧘", interests: ["Yoga", "Meditation", "Fitness", "Mental Health", "Nutrition"] },
  { name: "Tech", emoji: "💻", interests: ["Programming", "Design", "AI", "Gaming", "Startups"] },
  { name: "Social", emoji: "🎉", interests: ["Board Games", "Volunteering", "Travel", "Languages", "Pets"] },
];

export const valueOptions = [
  "Authenticity", "Compassion", "Creativity", "Community", "Growth",
  "Honesty", "Integrity", "Kindness", "Adventure", "Balance",
  "Respect", "Empathy", "Humor", "Curiosity", "Loyalty",
];
