project_id = "sqzeghkabqhhhiuidnvd"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.match-suggestions]
    verify_jwt = false
  [functions.ai-process-enrichment]
    verify_jwt = true
  [functions.recommend-feed]
    verify_jwt = true
