import { useState, type ReactNode } from 'react'
import { Heart, MapPin, Search, ShieldCheck, UsersRound } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Button, Card, Chip, Field, inputClass, SectionHeader } from '../components/ui'
import { communities, events } from '../lib/data'
import { useMockApp } from '../lib/mockApp'

export function Communities(){const nav=useNavigate(); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [saved,setSaved]=useState(new Set<string>()); const visible=communities.filter(c=>(category==='All'||c.category===category)&&(c.name+c.description).toLowerCase().includes(query.toLowerCase())); return <AppShell title="Discover Communities" subtitle="Explore spaces where real people connect around shared interests and values" action={<button aria-label="Filter communities" onClick={()=>nav('/communities/filter')} className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Search className="h-5 w-5"/></button>}><div className="space-y-5"><div className="relative"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full rounded-2xl border border-brand-line bg-white py-3.5 pl-12 pr-4 outline-none focus:border-brand-500" placeholder="Search communities, topics or keywords"/></div><div className="flex gap-2 overflow-x-auto pb-1 no-scrollbar">{['All','Wellness','Outdoors','Learning','Faith','Arts & Culture','Technology','Business'].map(x=><Chip key={x} active={category===x} onClick={()=>setCategory(x)}>{x}</Chip>)}</div><div className="grid gap-4 md:grid-cols-2">{visible.map(c=>{const favorite=saved.has(c.id); return <Card key={c.id} className="overflow-hidden"><img src={c.image} className="h-48 w-full object-cover"/><div className="p-5"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-lg font-extrabold">{c.name}{c.trusted&&<ShieldCheck className="h-5 w-5 text-emerald-600"/>}</div><div className="mt-1 flex items-center gap-2 text-xs text-brand-muted"><span>{c.members} members</span><span>·</span><span>{c.distance}</span></div></div><button aria-label="Save community" onClick={()=>setSaved(current=>{const next=new Set(current); favorite?next.delete(c.id):next.add(c.id);return next})}><Heart className={`h-5 w-5 ${favorite?'fill-brand-coral text-brand-coral':'text-slate-400'}`}/></button></div><div className="mt-3"><Chip tone={c.category==='Outdoors'?'green':'amber'}>{c.category}</Chip></div><p className="mt-3 text-sm text-slate-600">{c.description}</p><Button className="mt-5 w-full" onClick={()=>nav(`/communities/${c.id}`)}>View community</Button></div></Card>})}</div>{visible.length===0&&<Card className="p-8 text-center text-brand-muted">No communities match that search yet.</Card>}</div></AppShell>}

export function CommunityDetail(){const nav=useNavigate(); const {id}=useParams(); const { joinedCommunityIds,toggleCommunity }=useMockApp(); const [tab,setTab]=useState('About'); const c=communities.find(x=>x.id===id)||communities[0]; const e=events[0]; const joined=joinedCommunityIds.has(c.id); return <AppShell title={c.name} subtitle={`${c.members} members · ${c.distance}`}><div className="mx-auto max-w-4xl space-y-5"><Card className="overflow-hidden"><img src={c.image} className="h-72 w-full object-cover"/><div className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-2xl font-extrabold">{c.name}{c.trusted&&<ShieldCheck className="h-6 w-6 text-emerald-600"/>}</div><div className="mt-2 flex flex-wrap gap-2"><Chip tone="green">{c.category}</Chip><Chip>Local</Chip><Chip tone="gray">Active</Chip></div></div><div className="flex gap-2"><Button onClick={()=>toggleCommunity(c.id)}>{joined?'Joined ✓':'Join Community'}</Button><Button variant="secondary"><Heart className="h-4 w-4"/></Button></div></div><div className="mt-6 flex gap-6 border-b border-brand-line text-sm font-bold">{['About','Chat','Events','Members'].map(item=><button key={item} onClick={()=>{setTab(item);if(item==='Chat')nav('/messages/community')}} className={`pb-3 ${tab===item?'border-b-2 border-brand-500 text-brand-600':''}`}>{item}</button>)}</div>{tab==='About'?<><p className="mt-5 text-slate-600">{c.description} All experience levels are welcome. Respect, curiosity and participation keep this community healthy.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info icon={<MapPin/>} title="Austin, Texas, USA" detail={c.distance}/><Info icon={<UsersRound/>} title="Public Community" detail="Anyone can find and join"/></div></>:<div className="py-7 text-sm text-brand-muted">{tab} are available to members. Join this community to take part.</div>}</div></Card><Card className="p-5"><SectionHeader title="Upcoming event"/><div className="flex flex-col gap-4 sm:flex-row"><img src={e.image} className="h-36 w-full rounded-2xl object-cover sm:w-48"/><div className="flex-1"><div className="text-lg font-extrabold">{e.title}</div><div className="mt-1 text-sm text-brand-muted">{e.date} · {e.time} · {e.distance}</div><p className="mt-3 text-sm text-slate-600">Start your weekend with intention and meet people from the community in person.</p><Button variant="secondary" className="mt-4" onClick={()=>nav(`/events/${e.id}`)}>View event</Button></div></div></Card></div></AppShell>}

export function CreateCommunity(){return <AppShell title="Create Community" subtitle="Build a space where people belong"><div className="mx-auto max-w-2xl"><Card className="p-6"><div className="mb-6 flex gap-2">{[1,2,3,4,5].map(n=><div key={n} className={`grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${n===1?'bg-brand-500 text-white':'bg-brand-canvas text-brand-muted'}`}>{n}</div>)}</div><div className="space-y-5"><Field label="Community name"><input className={inputClass} placeholder="e.g. Austin Coffee Connect"/></Field><Field label="Category"><select className={inputClass}><option>Select a category</option><option>Outdoors</option><option>Wellness</option><option>Business</option></select></Field><Field label="Location"><input className={inputClass} defaultValue="Austin, Texas, USA"/></Field><Field label="Privacy"><select className={inputClass}><option>Public · Anyone can find and join</option><option>Approval required</option><option>Private</option></select></Field><Field label="Upload photo"><div className="grid h-40 place-items-center rounded-2xl border-2 border-dashed border-brand-line bg-brand-canvas text-center text-sm text-brand-muted"><div><UsersRound className="mx-auto mb-2 h-6 w-6 text-brand-500"/>Tap to upload a community photo</div></div></Field></div><Button className="mt-6 w-full">Continue</Button><button className="mt-3 w-full text-center text-sm font-semibold text-brand-600">Save draft</button></Card></div></AppShell>}

export function CommunityFilter(){return <AppShell title="Filter Communities" subtitle="Narrow discovery to the spaces that fit you"><div className="mx-auto max-w-2xl"><Card className="p-6"><Filter title="Category"><div className="flex flex-wrap gap-2">{['All','Wellness','Outdoors','Learning','Faith','Arts & Culture','Technology','Food','Business'].map((x,i)=><Chip key={x} active={i===0}>{x}</Chip>)}</div></Filter><Filter title="Distance"><input type="range" className="w-full accent-brand-500"/><div className="mt-1 flex justify-between text-xs text-brand-muted"><span>Any distance</span><span>50+ mi</span></div></Filter><Filter title="Group size"><div className="flex flex-wrap gap-2">{['Any size','Small (1–25)','Medium (26–100)','Large (100+)'].map((x,i)=><Chip key={x} active={i===0}>{x}</Chip>)}</div></Filter><Filter title="Activity"><div className="flex flex-wrap gap-2">{['Any','Low-key','Moderate','Very active'].map((x,i)=><Chip key={x} active={i===0}>{x}</Chip>)}</div></Filter><Button className="mt-6 w-full">Show Results (42)</Button></Card></div></AppShell>}
function Info({icon,title,detail}:{icon:ReactNode,title:string,detail:string}){return <div className="flex gap-3 rounded-2xl bg-brand-canvas p-4"><div className="text-brand-500">{icon}</div><div><div className="font-bold">{title}</div><div className="text-xs text-brand-muted">{detail}</div></div></div>}
function Filter({title,children}:{title:string,children:ReactNode}){return <div className="border-b border-brand-line py-5"><h3 className="mb-3 font-extrabold">{title}</h3>{children}</div>}
