import type { ReactNode } from 'react'
import { CalendarDays, Camera, Clock, Heart, MapPin, Search, Share2, ShieldCheck, UsersRound } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Button, Card, Chip, Field, inputClass } from '../components/ui'
import { events } from '../lib/data'

export function Events(){const nav=useNavigate(); return <AppShell title="Events" subtitle="What's happening near you"><div className="space-y-5"><div className="relative"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400"/><input className="w-full rounded-2xl border border-brand-line bg-white py-3.5 pl-12 pr-4 outline-none" placeholder="Search events, people or topics"/></div><div className="flex gap-2 overflow-x-auto no-scrollbar">{['For You','Today','This Week','Nearby'].map((x,i)=><Chip key={x} active={i===0}>{x}</Chip>)}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{events.map(e=><Card key={e.id} className="overflow-hidden"><div className="relative"><img src={e.image} className="h-52 w-full object-cover"/><div className="absolute left-3 top-3 rounded-xl bg-white px-3 py-2 text-center shadow"><div className="text-xs font-bold text-brand-coral">{e.date.split(' ')[0]}</div><div className="text-xl font-extrabold">{e.date.split(' ')[1]}</div></div><button className="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-white"><Heart className="h-5 w-5"/></button></div><div className="p-5"><div className="text-lg font-extrabold">{e.title}</div><div className="mt-1 text-sm text-brand-muted">{e.host}</div><div className="mt-4 space-y-2 text-sm text-slate-600"><div className="flex items-center gap-2"><Clock className="h-4 w-4 text-brand-500"/>{e.time}</div><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-brand-500"/>{e.distance} away</div><div className="flex items-center gap-2"><UsersRound className="h-4 w-4 text-brand-500"/>{e.attendees} going</div></div><Button className="mt-5 w-full" onClick={()=>nav(`/events/${e.id}`)}>View event</Button></div></Card>)}</div></div></AppShell>}

export function EventDetail(){const {id}=useParams(); const e=events.find(x=>x.id===id)||events[0]; return <AppShell title={e.title} subtitle={`${e.date} · ${e.time}`}><div className="mx-auto max-w-4xl space-y-5"><Card className="overflow-hidden"><div className="relative"><img src={e.image} className="h-80 w-full object-cover"/><button className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white"><Share2 className="h-5 w-5"/></button></div><div className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-3xl font-extrabold">{e.title}</h1><p className="mt-2 text-brand-muted">Hosted by {e.host}</p></div><Button variant="secondary">Follow host</Button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Info icon={<CalendarDays/>} title={e.date} detail={e.time}/><Info icon={<MapPin/>} title="Riverside Park" detail={`${e.distance} away`}/><Info icon={<UsersRound/>} title={`${e.attendees} going`} detail="People from nearby communities"/></div><div className="mt-5 h-44 rounded-2xl bg-[linear-gradient(135deg,#e7eef7_25%,#d9f0e6_25%,#d9f0e6_50%,#edf2f7_50%,#edf2f7_75%,#e7eef7_75%)] bg-[length:48px_48px] grid place-items-center"><MapPin className="h-8 w-8 fill-brand-500 text-white"/></div><h2 className="mt-6 text-lg font-extrabold">About this event</h2><p className="mt-2 text-slate-600">Start your weekend with intention. All levels are welcome. Bring what you need, show up with good energy, and meet people naturally.</p><div className="mt-5 flex gap-3 rounded-2xl bg-brand-50 p-4"><ShieldCheck className="h-5 w-5 text-brand-600"/><div><div className="font-bold text-brand-600">Safety first</div><div className="text-sm text-brand-muted">Respect community guidelines and only share location details that are necessary.</div></div></div></div></Card><Button className="sticky bottom-24 w-full lg:bottom-4">RSVP Now</Button></div></AppShell>}

export function CreateEvent(){return <AppShell title="Create Event" subtitle="Turn online discovery into a real-world connection"><div className="mx-auto max-w-2xl"><Card className="p-6"><Field label="Cover photo"><div className="grid h-48 place-items-center rounded-2xl border-2 border-dashed border-brand-line bg-brand-canvas"><Camera className="h-7 w-7 text-brand-500"/></div></Field><div className="mt-5 space-y-5"><Field label="Event title"><input className={inputClass} placeholder="e.g. Community Picnic in the Park"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><input type="date" className={inputClass}/></Field><Field label="Time"><input type="time" className={inputClass}/></Field></div><Field label="Location"><input className={inputClass} placeholder="Search for a location"/></Field><Field label="Description"><textarea rows={5} className={inputClass} placeholder="Tell people about your event..."/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Attendee limit"><input className={inputClass} defaultValue="50"/></Field><Field label="Community"><select className={inputClass}><option>Select a community</option></select></Field></div><Field label="Event type"><div className="flex flex-wrap gap-2">{['Wellness','Social','Learning','Volunteer'].map(x=><Chip key={x}>{x}</Chip>)}</div></Field></div><Button className="mt-6 w-full">Create Event</Button><p className="mt-3 text-center text-xs text-brand-muted">Events can be reviewed for safety and authenticity.</p></Card></div></AppShell>}
function Info({icon,title,detail}:{icon:ReactNode,title:string,detail:string}){return <div className="flex gap-3 rounded-2xl bg-brand-canvas p-4"><div className="text-brand-500">{icon}</div><div><div className="font-bold">{title}</div><div className="text-xs text-brand-muted">{detail}</div></div></div>}
