import type { ReactNode } from 'react'
import { Bell, CalendarDays, CheckCircle2, ChevronRight, Compass, MessageCircle, Search, Sparkles, UsersRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Avatar, Button, Card, Chip, SectionHeader, Verified } from '../components/ui'
import { communities, events, feedPosts, people } from '../lib/data'

export function Home(){const nav=useNavigate(); return <AppShell title="Good evening, Jane 👋" subtitle="Ready to meet your people?">
  <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
    <div className="space-y-7">
      <div className="relative"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400"/><input className="w-full rounded-2xl border border-brand-line bg-white py-3.5 pl-12 pr-4 shadow-sm outline-none focus:border-brand-500" placeholder="Search people, communities & events"/></div>
      <section><SectionHeader title="Your next connection" action={<button onClick={()=>nav('/matches')} className="text-sm font-bold text-brand-600">See all</button>}/><Card className="overflow-hidden"><div className="grid md:grid-cols-[250px_1fr]"><img className="h-56 w-full object-cover md:h-full" src={people[0].image}/><div className="p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-1.5 text-xl font-extrabold">{people[0].name}, {people[0].age}<Verified/></div><div className="mt-1 text-sm text-brand-muted">{people[0].city} · {people[0].distance}</div></div><div className="rounded-2xl bg-emerald-50 px-3 py-2 text-center"><div className="text-xl font-extrabold text-emerald-700">{people[0].match}%</div><div className="text-[10px] font-bold uppercase text-emerald-600">fit</div></div></div><p className="mt-4 text-sm text-slate-600">You both care about growth and community, and share hiking, books and local experiences.</p><div className="mt-4 flex flex-wrap gap-2">{people[0].interests.map(x=><Chip key={x}>{x}</Chip>)}</div><div className="mt-5 flex gap-3"><Button className="flex-1" onClick={()=>nav('/matches/maya')}>View profile</Button><Button variant="secondary">Say hello</Button></div></div></div></Card></section>
      <section><SectionHeader title="People you may click with"/><div className="grid gap-4 sm:grid-cols-2">{people.slice(1).map(p=><Card key={p.id} className="p-4"><div className="flex items-center gap-3"><Avatar src={p.image} name={p.name} size="lg"/><div className="min-w-0 flex-1"><div className="flex items-center gap-1 font-bold">{p.name}<Verified/></div><div className="text-xs text-brand-muted">{p.city}</div><div className="mt-2 flex flex-wrap gap-1">{p.interests.slice(0,2).map(x=><Chip key={x}>{x}</Chip>)}</div></div><div className="text-sm font-extrabold text-brand-600">{p.match}%</div></div></Card>)}</div></section>
      <section><SectionHeader title="Communities for you" action={<button onClick={()=>nav('/communities')} className="text-sm font-bold text-brand-600">Explore</button>}/><div className="grid gap-4 sm:grid-cols-2">{communities.slice(0,2).map(c=><Card key={c.id} className="overflow-hidden"><img src={c.image} className="h-40 w-full object-cover"/><div className="p-4"><div className="font-extrabold">{c.name}</div><div className="mt-1 text-xs text-brand-muted">{c.members} members · {c.distance}</div><p className="mt-2 line-clamp-2 text-sm text-slate-600">{c.description}</p><Button variant="secondary" className="mt-4 w-full" onClick={()=>nav(`/communities/${c.id}`)}>View community</Button></div></Card>)}</div></section>
      <section><SectionHeader title="From your feed" action={<button onClick={()=>nav('/feed')} className="text-sm font-bold text-brand-600">Open feed</button>}/>{feedPosts.slice(0,1).map(post=><Card key={post.id} className="overflow-hidden"><div className="flex items-center gap-3 p-4"><Avatar src={post.avatar} name={post.author}/><div><div className="flex items-center gap-1 font-bold">{post.author}<Verified/></div><div className="text-xs text-brand-muted">{post.time} · {post.tag}</div></div></div><p className="px-4 pb-4 text-sm">{post.text}</p><img src={post.image} className="max-h-[500px] w-full object-cover"/></Card>)}</section>
    </div>
    <aside className="space-y-5"><Card className="p-5"><SectionHeader title="Your highlights"/><div className="grid grid-cols-3 gap-3"><Stat value="80%" label="Profile"/><Stat value="3" label="Matches"/><Stat value="2" label="Events"/></div></Card><Card className="p-5"><SectionHeader title="Happening nearby"/>{events.slice(0,2).map(e=><button key={e.id} onClick={()=>nav(`/events/${e.id}`)} className="mb-3 flex w-full gap-3 text-left"><img src={e.image} className="h-16 w-20 rounded-xl object-cover"/><div className="min-w-0"><div className="truncate text-sm font-bold">{e.title}</div><div className="text-xs text-brand-muted">{e.date} · {e.time}</div><div className="mt-1 text-xs font-semibold text-brand-600">{e.distance}</div></div></button>)}</Card><Card className="p-5"><SectionHeader title="Quick start"/><div className="space-y-3"><Guide done icon={<CheckCircle2/>} title="Complete profile"/><Guide done icon={<Compass/>} title="Discover matches"/><Guide icon={<UsersRound/>} title="Join a community"/><Guide icon={<MessageCircle/>} title="Send a message"/><Guide icon={<CalendarDays/>} title="RSVP to an event"/></div></Card></aside>
  </div>
</AppShell>}

function Stat({value,label}:{value:string,label:string}){return <div className="rounded-2xl bg-brand-canvas p-3 text-center"><div className="text-xl font-extrabold text-brand-ink">{value}</div><div className="mt-1 text-[11px] font-semibold text-brand-muted">{label}</div></div>}
function Guide({done=false,icon,title}:{done?:boolean,icon:ReactNode,title:string}){return <div className="flex items-center gap-3 rounded-xl border border-brand-line p-3"><div className={`grid h-9 w-9 place-items-center rounded-xl ${done?'bg-emerald-50 text-emerald-600':'bg-brand-50 text-brand-600'}`}>{icon}</div><div className="flex-1 text-sm font-semibold">{title}</div><ChevronRight className="h-4 w-4 text-slate-400"/></div>}

export function Notifications(){return <AppShell title="Notifications" subtitle="Everything that needs your attention"><div className="mx-auto max-w-3xl"><div className="mb-5 flex flex-wrap gap-2">{['All','Messages','Connections','Communities','Events'].map((x,i)=><Chip key={x} active={i===0}>{x}</Chip>)}</div><div className="space-y-3">{[
  ['Maya Patel','sent you a message.','2m','message'],['Austin Hikers','posted a new Sunrise Hike event.','1h','event'],['You have 3 new matches!','Start a conversation while the match is fresh.','3h','match'],['Mindful Living Collective','invited you to join the community.','1d','community']
].map(([a,b,t,k])=><Card key={a} className="flex items-center gap-4 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600">{k==='message'?<MessageCircle/>:k==='event'?<CalendarDays/>:k==='community'?<UsersRound/>:<Sparkles/>}</div><div className="flex-1"><div className="font-bold">{a}</div><div className="text-sm text-brand-muted">{b}</div></div><div className="text-xs text-brand-muted">{t}</div></Card>)}</div></div></AppShell>}

export function QuickStart(){return <AppShell title="Quick Start Guide" subtitle="Get the most from Authentic Community Connection"><div className="mx-auto max-w-2xl"><Card className="p-6"><div className="mb-6"><div className="flex justify-between text-sm font-semibold"><span>2 of 5 completed</span><span className="text-brand-600">40%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full w-2/5 rounded-full bg-brand-500"/></div></div><div className="space-y-3"><Guide done icon={<CheckCircle2/>} title="Complete your profile"/><Guide done icon={<Compass/>} title="Discover matches"/><Guide icon={<UsersRound/>} title="Join a community"/><Guide icon={<MessageCircle/>} title="Send your first message"/><Guide icon={<CalendarDays/>} title="RSVP to an event"/></div></Card></div></AppShell>}
