import type { ReactNode } from 'react'
import { Bookmark, Check, Filter, MapPin, MessageCircle, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Button, Card, Chip, Verified } from '../components/ui'
import { people } from '../lib/data'

export function Matches(){const nav=useNavigate(); const p=people[0]; return <AppShell title="Discover Matches" subtitle="People nearby who align with your interests and values" action={<button onClick={()=>nav('/matches/filter')} className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><SlidersHorizontal className="h-5 w-5"/></button>}><div className="mx-auto max-w-xl"><Card className="overflow-hidden"><div className="relative"><img src={p.image} className="h-[52vh] min-h-[420px] w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 via-black/25 to-transparent p-5 pt-24 text-white"><div className="flex items-end justify-between gap-4"><div><div className="flex items-center gap-1.5 text-3xl font-extrabold">{p.name}, {p.age}<Verified/></div><div className="mt-1 flex items-center gap-1 text-sm text-white/80"><MapPin className="h-4 w-4"/>{p.city} · {p.distance}</div></div><div className="rounded-2xl bg-white/95 px-3 py-2 text-center text-brand-ink"><div className="text-2xl font-extrabold text-emerald-700">{p.match}%</div><div className="text-[10px] font-bold uppercase">match</div></div></div></div></div><div className="p-5"><div className="text-xs font-bold uppercase tracking-wide text-brand-muted">Shared interests</div><div className="mt-2 flex flex-wrap gap-2">{p.interests.map(x=><Chip key={x}>{x}</Chip>)}</div><div className="mt-4 text-xs font-bold uppercase tracking-wide text-brand-muted">Shared values</div><div className="mt-2 flex flex-wrap gap-2">{p.values.map(x=><Chip key={x} tone="green">{x}</Chip>)}</div><div className="mt-6 grid grid-cols-3 gap-3"><Button variant="secondary"><X className="h-5 w-5"/>Pass</Button><Button variant="secondary"><Bookmark className="h-5 w-5"/>Save</Button><Button onClick={()=>nav('/matches/maya')}><Sparkles className="h-5 w-5"/>Connect</Button></div></div></Card></div></AppShell>}

export function MatchDetail(){const p=people[0]; return <AppShell title={p.name} subtitle={`${p.match}% connection fit`}><div className="mx-auto max-w-3xl space-y-5"><Card className="overflow-hidden"><img src={p.image} className="h-80 w-full object-cover"/><div className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-1.5 text-2xl font-extrabold">{p.name}, {p.age}<Verified/></div><div className="mt-1 text-brand-muted">{p.city} · {p.distance}</div></div><div className="rounded-2xl bg-emerald-50 px-4 py-3 text-center"><div className="text-2xl font-extrabold text-emerald-700">{p.match}%</div><div className="text-xs font-semibold text-emerald-700">Connection fit</div></div></div><p className="mt-5 text-slate-600">Community builder, book lover and weekend hiker. Always up for meaningful conversations and trying new local spots.</p><div className="mt-6 grid gap-3 sm:grid-cols-4"><Trust title="Identity verified"/><Trust title="Active this week"/><Trust title="Community contributor"/><Trust title="Positive interactions"/></div></div></Card><Card className="p-6"><h2 className="text-lg font-extrabold">Why you may click</h2><div className="mt-4 space-y-3"><Reason text="You both consider personal growth and community important."/><Reason text="You share hiking, books, travel and local experiences."/><Reason text="You are both active in Austin communities."/></div></Card><Card className="p-6"><div className="flex items-center gap-2 font-extrabold"><Sparkles className="h-5 w-5 text-brand-500"/>Conversation starters</div><div className="mt-4 space-y-2"><Starter text="What's a book that changed your perspective?"/><Starter text="What's your favorite local trail around Austin?"/><Starter text="What kind of community would you love to help build?"/></div></Card><Button className="sticky bottom-24 w-full lg:bottom-4"><MessageCircle className="h-5 w-5"/>Connect with Maya</Button></div></AppShell>}

export function MatchFilter(){return <AppShell title="Filter Matches" subtitle="Tune who appears in your discovery feed"><div className="mx-auto max-w-2xl"><Card className="p-6"><FilterBlock title="Distance"><input type="range" className="w-full accent-brand-500" defaultValue={25}/><div className="mt-1 flex justify-between text-xs text-brand-muted"><span>5 mi</span><span>25 mi</span><span>100+ mi</span></div></FilterBlock><FilterBlock title="Age range"><div className="grid grid-cols-2 gap-3"><input className="rounded-xl border border-brand-line p-3" defaultValue="22"/><input className="rounded-xl border border-brand-line p-3" defaultValue="40"/></div></FilterBlock><FilterBlock title="Interests"><div className="flex flex-wrap gap-2">{['Hiking','Books','Community','Travel','Yoga','Music','Art','Tech'].map((x,i)=><Chip key={x} active={i<3}>{x}</Chip>)}</div></FilterBlock><FilterBlock title="Values"><div className="flex flex-wrap gap-2">{['Kindness','Growth','Community','Learning','Creativity','Honesty'].map((x,i)=><Chip key={x} active={i<3}>{x}</Chip>)}</div></FilterBlock><div className="mt-6 flex items-center justify-between rounded-2xl bg-brand-canvas p-4"><div><div className="font-bold">Verified only</div><div className="text-xs text-brand-muted">Show identity-verified profiles</div></div><div className="h-7 w-12 rounded-full bg-emerald-500 p-1"><div className="ml-auto h-5 w-5 rounded-full bg-white"/></div></div><Button className="mt-6 w-full">Show 34 people</Button></Card></div></AppShell>}

export function MatchSort(){return <AppShell title="Sort Matches" subtitle="Choose how your discovery feed is ordered"><div className="mx-auto max-w-xl"><Card className="overflow-hidden">{[
  ['Newest','Recently joined'],['Best Match','Highest connection-fit score'],['Nearest','Closest to you'],['Most Active','Recently active'],['Shared Values','Most aligned values']
].map(([title,detail],i)=><button key={title} className={`flex w-full items-center gap-4 border-b border-brand-line p-5 text-left last:border-none ${i===1?'bg-brand-50':''}`}><div className={`grid h-10 w-10 place-items-center rounded-xl ${i===1?'bg-brand-500 text-white':'bg-brand-canvas text-brand-muted'}`}><Sparkles className="h-5 w-5"/></div><div className="flex-1"><div className="font-bold">{title}</div><div className="text-sm text-brand-muted">{detail}</div></div><div className={`grid h-5 w-5 place-items-center rounded-full border ${i===1?'border-brand-500 bg-brand-500 text-white':'border-slate-300'}`}>{i===1&&<Check className="h-3 w-3"/>}</div></button>)}</Card></div></AppShell>}

function Trust({title}:{title:string}){return <div className="rounded-2xl bg-brand-canvas p-4 text-center"><Check className="mx-auto h-5 w-5 text-emerald-600"/><div className="mt-2 text-xs font-semibold">{title}</div></div>}
function Reason({text}:{text:string}){return <div className="flex gap-3 rounded-xl bg-brand-canvas p-4"><Check className="h-5 w-5 shrink-0 text-emerald-600"/><span className="text-sm text-slate-700">{text}</span></div>}
function Starter({text}:{text:string}){return <button className="flex w-full items-center justify-between rounded-xl border border-brand-line p-4 text-left text-sm hover:border-brand-500"><span>{text}</span><MessageCircle className="h-4 w-4 text-brand-500"/></button>}
function FilterBlock({title,children}:{title:string,children:ReactNode}){return <div className="border-b border-brand-line py-5 last:border-none"><h3 className="mb-3 font-extrabold">{title}</h3>{children}</div>}
