import { useState, type ReactNode } from 'react'
import { Bookmark, Check, Filter, MapPin, MessageCircle, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Button, Card, Chip, Verified } from '../components/ui'
import { people } from '../lib/data'
import { useMockApp } from '../lib/mockApp'

export function Matches(){const nav=useNavigate(); const { passedMatchIds, savedMatchIds, passMatch, toggleSavedMatch, toast }=useMockApp(); const p=people.find(person=>!passedMatchIds.has(person.id)) ?? people[0]; const saved=savedMatchIds.has(p.id); return <AppShell title="Discover Matches" subtitle="People nearby who align with your interests and values" action={<div className="flex gap-2"><button aria-label="Sort matches" onClick={()=>nav('/matches/sort')} className="grid h-10 w-10 place-items-center rounded-xl bg-white text-brand-600 shadow-sm"><Sparkles className="h-5 w-5"/></button><button aria-label="Filter matches" onClick={()=>nav('/matches/filter')} className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><SlidersHorizontal className="h-5 w-5"/></button></div>}><div className="mx-auto max-w-xl"><Card className="overflow-hidden"><div className="relative"><img src={p.image} className="h-[52vh] min-h-[420px] w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 via-black/25 to-transparent p-5 pt-24 text-white"><div className="flex items-end justify-between gap-4"><div><div className="flex items-center gap-1.5 text-3xl font-extrabold">{p.name}, {p.age}<Verified/></div><div className="mt-1 flex items-center gap-1 text-sm text-white/80"><MapPin className="h-4 w-4"/>{p.city} · {p.distance}</div></div><div className="rounded-2xl bg-white/95 px-3 py-2 text-center text-brand-ink"><div className="text-2xl font-extrabold text-emerald-700">{p.match}%</div><div className="text-[10px] font-bold uppercase">match</div></div></div></div></div><div className="p-5"><div className="text-xs font-bold uppercase tracking-wide text-brand-muted">Shared interests</div><div className="mt-2 flex flex-wrap gap-2">{p.interests.map(x=><Chip key={x}>{x}</Chip>)}</div><div className="mt-4 text-xs font-bold uppercase tracking-wide text-brand-muted">Shared values</div><div className="mt-2 flex flex-wrap gap-2">{p.values.map(x=><Chip key={x} tone="green">{x}</Chip>)}</div><div className="mt-6 grid grid-cols-3 gap-3"><Button variant="secondary" onClick={()=>passMatch(p.id)}><X className="h-5 w-5"/>Pass</Button><Button variant="secondary" onClick={()=>toggleSavedMatch(p.id)}><Bookmark className={`h-5 w-5 ${saved?'fill-brand-500':''}`}/>{saved?'Saved':'Save'}</Button><Button onClick={()=>{toast(`Connection request sent to ${p.name}`);nav(`/matches/${p.id}`)}}><Sparkles className="h-5 w-5"/>Connect</Button></div></div></Card></div></AppShell>}

export function MatchDetail(){const nav=useNavigate(); const { toast }=useMockApp(); const p=people[0]; return <AppShell title={p.name} subtitle={`${p.match}% connection fit`}><div className="mx-auto max-w-3xl space-y-5"><Card className="overflow-hidden"><img src={p.image} className="h-80 w-full object-cover"/><div className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-1.5 text-2xl font-extrabold">{p.name}, {p.age}<Verified/></div><div className="mt-1 text-brand-muted">{p.city} · {p.distance}</div></div><div className="rounded-2xl bg-emerald-50 px-4 py-3 text-center"><div className="text-2xl font-extrabold text-emerald-700">{p.match}%</div><div className="text-xs font-semibold text-emerald-700">Connection fit</div></div></div><p className="mt-5 text-slate-600">Community builder, book lover and weekend hiker. Always up for meaningful conversations and trying new local spots.</p><div className="mt-6 grid gap-3 sm:grid-cols-4"><Trust title="Identity verified"/><Trust title="Active this week"/><Trust title="Community contributor"/><Trust title="Positive interactions"/></div></div></Card><Card className="p-6"><h2 className="text-lg font-extrabold">Why you may click</h2><div className="mt-4 space-y-3"><Reason text="You both consider personal growth and community important."/><Reason text="You share hiking, books, travel and local experiences."/><Reason text="You are both active in Austin communities."/></div></Card><Card className="p-6"><div className="flex items-center gap-2 font-extrabold"><Sparkles className="h-5 w-5 text-brand-500"/>Conversation starters</div><div className="mt-4 space-y-2"><Starter text="What's a book that changed your perspective?"/><Starter text="What's your favorite local trail around Austin?"/><Starter text="What kind of community would you love to help build?"/></div></Card><Button className="sticky bottom-24 w-full lg:bottom-4" onClick={()=>{toast('Connection request sent to Maya'); nav('/messages/direct')}}><MessageCircle className="h-5 w-5"/>Connect with Maya</Button></div></AppShell>}

export function MatchFilter(){const nav=useNavigate(); const [interests,setInterests]=useState(['Hiking','Books','Community']); const [values,setValues]=useState(['Kindness','Growth','Community']); const [verified,setVerified]=useState(true); const toggle=(set:(v:string[])=>void,list:string[],value:string)=>set(list.includes(value)?list.filter(x=>x!==value):[...list,value]); return <AppShell title="Filter Matches" subtitle="Tune who appears in your discovery feed"><div className="mx-auto max-w-2xl"><Card className="p-6"><FilterBlock title="Distance"><input aria-label="Distance" type="range" className="w-full accent-brand-500" defaultValue={25}/><div className="mt-1 flex justify-between text-xs text-brand-muted"><span>5 mi</span><span>25 mi</span><span>100+ mi</span></div></FilterBlock><FilterBlock title="Age range"><div className="grid grid-cols-2 gap-3"><input aria-label="Minimum age" className="rounded-xl border border-brand-line p-3" defaultValue="22"/><input aria-label="Maximum age" className="rounded-xl border border-brand-line p-3" defaultValue="40"/></div></FilterBlock><FilterBlock title="Interests"><div className="flex flex-wrap gap-2">{['Hiking','Books','Community','Travel','Yoga','Music','Art','Tech'].map(x=><Chip key={x} active={interests.includes(x)} onClick={()=>toggle(setInterests,interests,x)}>{x}</Chip>)}</div></FilterBlock><FilterBlock title="Values"><div className="flex flex-wrap gap-2">{['Kindness','Growth','Community','Learning','Creativity','Honesty'].map(x=><Chip key={x} active={values.includes(x)} onClick={()=>toggle(setValues,values,x)}>{x}</Chip>)}</div></FilterBlock><button type="button" onClick={()=>setVerified(!verified)} className="mt-6 flex w-full items-center justify-between rounded-2xl bg-brand-canvas p-4 text-left"><div><div className="font-bold">Verified only</div><div className="text-xs text-brand-muted">Show identity-verified profiles</div></div><div className={`h-7 w-12 rounded-full p-1 ${verified?'bg-emerald-500':'bg-slate-300'}`}><div className={`h-5 w-5 rounded-full bg-white ${verified?'ml-auto':''}`}/></div></button><Button className="mt-6 w-full" onClick={()=>nav('/matches')}>Show 34 people</Button></Card></div></AppShell>}

export function MatchSort(){const nav=useNavigate(); const [selected,setSelected]=useState('Best Match'); return <AppShell title="Sort Matches" subtitle="Choose how your discovery feed is ordered"><div className="mx-auto max-w-xl"><Card className="overflow-hidden">{[
  ['Newest','Recently joined'],['Best Match','Highest connection-fit score'],['Nearest','Closest to you'],['Most Active','Recently active'],['Shared Values','Most aligned values']
].map(([title,detail])=>{const active=selected===title; return <button key={title} onClick={()=>{setSelected(title); window.setTimeout(()=>nav('/matches'),180)}} className={`flex w-full items-center gap-4 border-b border-brand-line p-5 text-left last:border-none ${active?'bg-brand-50':''}`}><div className={`grid h-10 w-10 place-items-center rounded-xl ${active?'bg-brand-500 text-white':'bg-brand-canvas text-brand-muted'}`}><Sparkles className="h-5 w-5"/></div><div className="flex-1"><div className="font-bold">{title}</div><div className="text-sm text-brand-muted">{detail}</div></div><div className={`grid h-5 w-5 place-items-center rounded-full border ${active?'border-brand-500 bg-brand-500 text-white':'border-slate-300'}`}>{active&&<Check className="h-3 w-3"/>}</div></button>})}</Card></div></AppShell>}

function Trust({title}:{title:string}){return <div className="rounded-2xl bg-brand-canvas p-4 text-center"><Check className="mx-auto h-5 w-5 text-emerald-600"/><div className="mt-2 text-xs font-semibold">{title}</div></div>}
function Reason({text}:{text:string}){return <div className="flex gap-3 rounded-xl bg-brand-canvas p-4"><Check className="h-5 w-5 shrink-0 text-emerald-600"/><span className="text-sm text-slate-700">{text}</span></div>}
function Starter({text}:{text:string}){return <button className="flex w-full items-center justify-between rounded-xl border border-brand-line p-4 text-left text-sm hover:border-brand-500"><span>{text}</span><MessageCircle className="h-4 w-4 text-brand-500"/></button>}
function FilterBlock({title,children}:{title:string,children:ReactNode}){return <div className="border-b border-brand-line py-5 last:border-none"><h3 className="mb-3 font-extrabold">{title}</h3>{children}</div>}
