import type { ReactNode } from 'react'
import { Bot, ChevronLeft, Image, Mic, MoreHorizontal, Plus, Search, Send, Smile, UsersRound } from 'lucide-react'
import { AppShell } from '../components/AppShell'
import { Avatar, Card, Chip, Verified } from '../components/ui'
import { messages, people } from '../lib/data'

export function Messages(){return <AppShell title="Messages" subtitle="Direct conversations and community chats"><div className="mx-auto max-w-3xl"><div className="mb-4 grid grid-cols-2 rounded-2xl border border-brand-line bg-white p-1"><button className="rounded-xl bg-brand-500 py-2.5 text-sm font-bold text-white">Direct</button><button className="rounded-xl py-2.5 text-sm font-bold text-brand-muted">Communities</button></div><div className="relative mb-4"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400"/><input className="w-full rounded-2xl border border-brand-line bg-white py-3.5 pl-12 pr-4" placeholder="Search messages"/></div><Card className="divide-y divide-brand-line overflow-hidden">{messages.map(m=><div key={m.name} className="flex items-center gap-3 p-4 hover:bg-slate-50"><Avatar src={m.image} name={m.name} online={m.online}/><div className="min-w-0 flex-1"><div className="truncate font-bold">{m.name}</div><div className="truncate text-sm text-brand-muted">{m.text}</div></div><div className="text-right"><div className="text-[11px] text-brand-muted">{m.time}</div>{m.unread>0&&<div className="ml-auto mt-2 grid h-5 min-w-5 place-items-center rounded-full bg-brand-500 px-1 text-[10px] font-bold text-white">{m.unread}</div>}</div></div>)}</Card></div></AppShell>}

export function DirectChat(){const p=people[0]; return <AppShell title="Maya Patel" subtitle="Online · 92% match"><div className="mx-auto max-w-3xl"><Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-brand-line p-4"><Avatar src={p.image} name={p.name} online/><div className="flex-1"><div className="flex items-center gap-1 font-bold">{p.name}<Verified/></div><div className="text-xs text-emerald-600">Online</div></div><Chip active>{p.match}% Match</Chip><MoreHorizontal/></div><div className="min-h-[55vh] space-y-4 bg-white p-5"><Bubble>Hey! 😊 Thanks for connecting.</Bubble><Bubble mine>Great to meet you too. I saw we're both into hiking and books.</Bubble><Bubble>Same here. Do you have a favorite trail around Austin?</Bubble><Bubble mine>The Barton Creek Greenbelt is my go-to. Want to plan a hike sometime?</Bubble><Bubble>That sounds fun. Saturday morning could work!</Bubble><div className="rounded-2xl border border-brand-500/20 bg-brand-50 p-4"><div className="flex items-center gap-2 text-sm font-bold text-brand-600"><Bot className="h-4 w-4"/>AI Icebreaker Suggestion</div><div className="mt-1 text-sm text-brand-muted">Ask about her favorite photo spots around Austin.</div></div></div><Composer/></Card></div></AppShell>}

export function CommunityChat(){return <AppShell title="Mindful Living Community" subtitle="248 members · 18 online"><div className="mx-auto max-w-3xl"><Card className="overflow-hidden"><div className="border-b border-brand-line bg-brand-50 p-4 text-sm"><div className="font-bold text-brand-600">📌 Pinned announcement</div><div className="text-brand-muted">Friday meditation session at 7:00 AM. Join us!</div></div><div className="min-h-[55vh] space-y-5 p-5"><GroupMsg name="Alex Johnson" text="Good morning, beautiful souls! How is everyone's week going?"/><GroupMsg name="Sarah Williams" text="Feeling grateful and grounded today. The morning meditation really helped."/><GroupMsg name="Marcus Lee" text="Don't forget about our community nature walk this Saturday!"/><div className="rounded-2xl border border-brand-line p-4"><div className="flex items-center gap-2 font-bold"><UsersRound className="h-5 w-5 text-brand-sage"/>Nature Walk at Zilker Park</div><div className="mt-1 text-sm text-brand-muted">Sat · 8:00 AM · 15 people going</div><button className="mt-3 text-sm font-bold text-brand-600">View event</button></div></div><Composer community/></Card></div></AppShell>}

function Bubble({children,mine=false}:{children:ReactNode,mine?:boolean}){return <div className={`flex ${mine?'justify-end':''}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm ${mine?'bg-brand-500 text-white':'bg-slate-100 text-brand-ink'}`}>{children}</div></div>}
function GroupMsg({name,text}:{name:string,text:string}){return <div className="flex gap-3"><Avatar name={name}/><div><div className="text-sm font-bold">{name}</div><div className="mt-1 rounded-2xl rounded-tl-md bg-slate-100 px-4 py-3 text-sm">{text}</div><div className="mt-1 text-xs text-brand-muted">❤️ 12 · 🙌 6 · Reply</div></div></div>}
function Composer({community=false}:{community?:boolean}){return <div className="flex items-center gap-2 border-t border-brand-line bg-white p-3"><button className="grid h-10 w-10 place-items-center rounded-xl bg-brand-500 text-white"><Plus className="h-5 w-5"/></button><div className="flex flex-1 items-center rounded-xl bg-brand-canvas px-3"><input className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" placeholder={community?'Message #general':'Type a message...'}/><Smile className="h-5 w-5 text-slate-400"/></div><button className="grid h-10 w-10 place-items-center rounded-xl text-brand-muted"><Mic className="h-5 w-5"/></button><button className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Send className="h-5 w-5"/></button></div>}
