import { useState, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { Camera, Check, ChevronLeft, MapPin, Search, Sparkles } from 'lucide-react'
import { Button, Card, Chip, Field, inputClass } from '../components/ui'

function Frame({step, children}:{step:number, children:ReactNode}) {
 const navigate=useNavigate()
 return <div className="min-h-screen bg-brand-canvas px-4 py-6 sm:py-10"><div className="mx-auto max-w-2xl"><button onClick={()=>navigate(-1)} className="mb-5 grid h-10 w-10 place-items-center rounded-xl bg-white shadow-sm"><ChevronLeft/></button><Card className="p-5 sm:p-8"><div className="mb-8"><div className="flex items-center justify-between text-xs font-semibold text-brand-muted"><span>Profile setup</span><span>Step {step} of 4</span></div><div className="mt-3 grid grid-cols-4 gap-2">{[1,2,3,4].map(n=><div key={n} className={`h-1.5 rounded-full ${n<=step?'bg-brand-500':'bg-slate-200'}`}/>)}</div></div>{children}</Card></div></div>
}

export function OnboardingLocation(){const nav=useNavigate(); const [radius,setRadius]=useState('10 mi'); const [cityOnly,setCityOnly]=useState(true); return <Frame step={1}><h1 className="text-3xl font-extrabold">Where are you based?</h1><p className="mt-2 text-brand-muted">We'll show you people, communities and events nearby. Your exact location stays private.</p><div className="mt-7"><Field label="City"><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input className={`${inputClass} pl-10`} defaultValue="Austin, Texas, USA"/></div></Field></div><div className="relative mt-4 h-64 overflow-hidden rounded-2xl bg-[linear-gradient(135deg,#e7eef7_25%,#d9f0e6_25%,#d9f0e6_50%,#edf2f7_50%,#edf2f7_75%,#e7eef7_75%)] bg-[length:48px_48px]"><div className="absolute inset-0 grid place-items-center"><div className="grid h-32 w-32 place-items-center rounded-full bg-brand-500/10 ring-2 ring-brand-500/30"><MapPin className="h-9 w-9 fill-brand-500 text-white"/></div></div></div><h3 className="mt-6 font-bold">How far are you open to connect?</h3><div className="mt-3 flex flex-wrap gap-2">{['5 mi','10 mi','25 mi','50 mi','100+ mi'].map(x=><Chip key={x} active={radius===x} onClick={()=>setRadius(x)}>{x}</Chip>)}</div><button type="button" onClick={()=>setCityOnly(!cityOnly)} className="mt-6 flex w-full items-center justify-between rounded-2xl bg-emerald-50 p-4 text-left"><div><div className="font-semibold text-emerald-900">Show my city, not exact location</div><div className="text-xs text-emerald-700">Recommended for privacy</div></div><div className={`h-7 w-12 rounded-full p-1 ${cityOnly?'bg-emerald-500':'bg-slate-300'}`}><div className={`h-5 w-5 rounded-full bg-white ${cityOnly?'ml-auto':''}`}/></div></button><Button className="mt-7 w-full" onClick={()=>nav('/onboarding/interests')}>Continue</Button></Frame>}

export function OnboardingInterests(){const nav=useNavigate(); const items=['Design','Gaming','Fitness','Books','Technology','Music','Travel','Entrepreneurship','Photography','Startups','Hiking','Food']; const [selected,setSelected]=useState(['Design','Books','Travel','Entrepreneurship']); const [level,setLevel]=useState('Enthusiast'); const toggle=(item:string)=>setSelected(current=>current.includes(item)?current.filter(value=>value!==item):current.length<5?[...current,item]:current); return <Frame step={2}><h1 className="text-3xl font-extrabold">What are you into?</h1><p className="mt-2 text-brand-muted">Pick up to 5 interests to find your people ({selected.length}/5).</p><div className="mt-7 flex flex-wrap gap-2">{items.map((x,i)=>{const active=selected.includes(x);return <Chip key={x} tone={i%4===0?'green':i%4===1?'coral':i%4===2?'amber':'indigo'} active={active} onClick={()=>toggle(x)}>{active&&<Check className="h-3 w-3"/>}{x}</Chip>})}</div><h3 className="mt-8 font-bold">Your proficiency (optional)</h3><div className="mt-3 flex gap-2">{['Beginner','Enthusiast','Expert'].map(item=><Chip key={item} active={level===item} onClick={()=>setLevel(item)}>{item}</Chip>)}</div><Button className="mt-8 w-full" onClick={()=>nav('/onboarding/values')}>Continue</Button></Frame>}

export function OnboardingValues(){const nav=useNavigate(); const items=['Kindness','Growth','Honesty','Family','Creativity','Community','Faith','Health','Learning','Adventure','Freedom']; const [selected,setSelected]=useState(['Kindness','Growth','Honesty','Community']); const [importance,setImportance]=useState('Important'); const toggle=(item:string)=>setSelected(current=>current.includes(item)?current.filter(value=>value!==item):current.length<5?[...current,item]:current); return <Frame step={3}><h1 className="text-3xl font-extrabold">What matters most to you?</h1><p className="mt-2 text-brand-muted">Choose the values that guide you.</p><div className="mt-7 flex flex-wrap gap-2">{items.map((x,i)=>{const active=selected.includes(x);return <Chip key={x} tone={i%3===0?'green':i%3===1?'indigo':'amber'} active={active} onClick={()=>toggle(x)}>{active&&<Check className="h-3 w-3"/>}{x}</Chip>})}</div><h3 className="mt-8 font-bold">How important are these values to you?</h3><div className="mt-3 flex gap-2">{['Somewhat','Important','Essential'].map(item=><Chip key={item} active={importance===item} onClick={()=>setImportance(item)}>{item}</Chip>)}</div><Button className="mt-8 w-full" onClick={()=>nav('/onboarding/bio')}>Continue</Button></Frame>}

export function OnboardingBio(){const nav=useNavigate(); return <Frame step={4}><h1 className="text-3xl font-extrabold">Show people the real you.</h1><p className="mt-2 text-brand-muted">A clear photo and honest bio make better introductions.</p><div className="mx-auto mt-8 grid h-32 w-32 place-items-center rounded-full bg-brand-50 ring-4 ring-white shadow-soft"><Camera className="h-8 w-8 text-brand-500"/></div><div className="mt-7"><Field label="Bio"><textarea rows={5} className={inputClass} defaultValue="Designer by day, coffee enthusiast always. I love great conversations, local adventures and building meaningful connections."/></Field></div><button className="mt-4 flex w-full items-center gap-3 rounded-2xl border border-brand-500/20 bg-brand-50 p-4 text-left"><Sparkles className="h-5 w-5 text-brand-500"/><div><div className="font-bold text-brand-600">AI Assist</div><div className="text-xs text-brand-muted">Help me make this sound natural, not robotic.</div></div></button><Button className="mt-7 w-full" onClick={()=>nav('/home')}>Finish & Explore</Button></Frame>}
