import { useState, type ReactNode } from 'react'
import { BadgeCheck, Camera, Edit3, MessageCircle, Search, Settings, ShieldCheck, Star, UsersRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Avatar, Button, Card, Chip, Field, inputClass, SectionHeader, Verified } from '../components/ui'
import { communities, people } from '../lib/data'
import { useMockApp } from '../lib/mockApp'

export function Profile(){const nav=useNavigate(); return <AppShell title="My Profile" subtitle="Your public identity and trust signals" action={<button onClick={()=>nav('/settings')} className="grid h-10 w-10 place-items-center rounded-xl border border-brand-line bg-white"><Settings className="h-5 w-5"/></button>}><div className="mx-auto max-w-4xl space-y-5"><Card className="p-6"><div className="flex flex-col items-center text-center"><Avatar src={people[0].image} name="Jane Doe" size="xl"/><div className="mt-4 flex items-center gap-1.5 text-2xl font-extrabold">Jane Doe<Verified/></div><div className="mt-1 text-sm text-brand-muted">Austin, Texas, USA</div><p className="mt-4 max-w-xl text-slate-600">Community builder, nature lover and lifelong learner. I believe in kindness, curiosity and making meaningful connections.</p><div className="mt-5 flex flex-wrap justify-center gap-2"><Chip>1,248 Followers</Chip><Chip>382 Following</Chip><Chip tone="green">97 Connections</Chip></div></div><div className="mt-7 grid gap-3 sm:grid-cols-4"><Trust icon={<BadgeCheck/>} label="Identity verified"/><Trust icon={<ShieldCheck/>} label="Profile complete"/><Trust icon={<UsersRound/>} label="Community contributor"/><Trust icon={<Star/>} label="Positive interactions"/></div><div className="mt-7 grid gap-6 md:grid-cols-2"><div><SectionHeader title="Interests"/><div className="flex flex-wrap gap-2">{['Hiking','Books','Mindfulness','Music','Travel'].map(x=><Chip key={x}>{x}</Chip>)}</div></div><div><SectionHeader title="Values"/><div className="flex flex-wrap gap-2">{['Kindness','Honesty','Growth','Learning'].map(x=><Chip key={x} tone="green">{x}</Chip>)}</div></div></div><div className="mt-7"><div className="flex justify-between text-sm font-semibold"><span>Profile completion</span><span>85%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full w-[85%] rounded-full bg-brand-500"/></div></div><Button className="mt-6 w-full" onClick={()=>nav('/profile/edit')}><Edit3 className="h-4 w-4"/>Edit Profile</Button></Card></div></AppShell>}

export function EditProfile(){const nav=useNavigate(); const {toast}=useMockApp(); const [interests,setInterests]=useState(['Hiking','Books','Mindfulness','Music','Travel']); const [values,setValues]=useState(['Kindness','Honesty','Growth','Learning']); const remove=(value:string,set:(items:string[])=>void,items:string[])=>set(items.filter(item=>item!==value)); return <AppShell title="Edit Profile" subtitle="Keep your profile current and human"><div className="mx-auto max-w-2xl"><Card className="p-6"><div className="flex justify-center"><div className="relative"><Avatar src={people[0].image} name="Jane Doe" size="xl"/><button onClick={()=>toast('Photo picker is ready for your media upload service')} className="absolute bottom-0 right-0 grid h-9 w-9 place-items-center rounded-full bg-brand-500 text-white"><Camera className="h-4 w-4"/></button></div></div><div className="mt-7 space-y-5"><Field label="Full name"><input className={inputClass} defaultValue="Jane Doe"/></Field><Field label="Location"><input className={inputClass} defaultValue="Austin, Texas, USA"/></Field><Field label="Bio"><textarea rows={5} className={inputClass} defaultValue="Community builder, nature lover and lifelong learner. I believe in kindness, curiosity and making meaningful connections."/></Field><Field label="Interests"><div className="flex flex-wrap gap-2">{interests.map(x=><Chip key={x} onClick={()=>remove(x,setInterests,interests)}>{x} ×</Chip>)}<Chip tone="gray" onClick={()=>setInterests(current=>current.includes('Photography')?current:[...current,'Photography'])}>+ Add interest</Chip></div></Field><Field label="Values"><div className="flex flex-wrap gap-2">{values.map(x=><Chip key={x} tone="green" onClick={()=>remove(x,setValues,values)}>{x} ×</Chip>)}<Chip tone="gray" onClick={()=>setValues(current=>current.includes('Community')?current:[...current,'Community'])}>+ Add value</Chip></div></Field></div><div className="mt-6 grid grid-cols-2 gap-3"><Button variant="secondary" onClick={()=>nav('/profile')}>Cancel</Button><Button onClick={()=>{toast('Profile changes saved');nav('/profile')}}>Save changes</Button></div></Card></div></AppShell>}

export function Connections(){const nav=useNavigate(); const [tab,setTab]=useState('All connections'); return <AppShell title="My Connections" subtitle="People you've mutually chosen to know"><div className="mx-auto max-w-3xl"><div className="mb-4 flex gap-2">{['All connections','Recent','Favorites'].map(item=><Chip key={item} active={tab===item} onClick={()=>setTab(item)}>{item}</Chip>)}</div><div className="space-y-3">{people.concat(people[0]).map((p,i)=><Card key={`${p.id}-${i}`} className="flex items-center gap-4 p-4"><Avatar src={p.image} name={p.name} size="lg"/><div className="min-w-0 flex-1"><div className="flex items-center gap-1 font-bold">{p.name}<Verified/></div><div className="text-xs text-brand-muted">{p.city} · Last interacted {i+2} days ago</div><div className="mt-2 flex gap-1">{p.interests.slice(0,2).map(x=><Chip key={x}>{x}</Chip>)}</div></div><Button variant="secondary" onClick={()=>nav('/messages/direct')}><MessageCircle className="h-4 w-4"/>Message</Button></Card>)}</div></div></AppShell>}

export function MyCommunities(){return <AppShell title="My Communities" subtitle="Spaces where you belong"><div className="mx-auto max-w-4xl"><div className="mb-4 flex gap-2"><Chip active>Joined</Chip><Chip>Discover</Chip><Chip>Invites 2</Chip></div><div className="grid gap-4 md:grid-cols-2">{communities.slice(0,3).map((c,i)=><Card key={c.id} className="overflow-hidden"><img src={c.image} className="h-40 w-full object-cover"/><div className="p-4"><div className="flex items-center justify-between"><div className="font-extrabold">{c.name}</div><Chip tone="green">{i===0?'Admin':i===1?'Moderator':'Member'}</Chip></div><div className="mt-1 text-xs text-brand-muted">{c.members} members</div><p className="mt-2 text-sm text-slate-600">{c.description}</p><Button className="mt-4 w-full">View</Button></div></Card>)}</div><Button variant="secondary" className="mt-5 w-full">+ Create a Community</Button></div></AppShell>}

export function Followers(){const [tab,setTab]=useState('Followers'); const {followedIds,toggleFollow}=useMockApp(); return <AppShell title="Followers & Following" subtitle="Your audience, your interests and your real connections"><div className="mx-auto max-w-3xl"><div className="mb-4 grid grid-cols-3 rounded-2xl bg-white p-1 shadow-sm">{['Followers','Following','Connections'].map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-xl py-2 text-sm font-bold ${tab===item?'bg-brand-500 text-white':'text-brand-muted'}`}>{item}</button>)}</div><div className="space-y-3">{people.map((p,i)=>{const following=followedIds.has(p.id); return <Card key={p.id} className="flex items-center gap-4 p-4"><Avatar src={p.image} name={p.name} size="lg"/><div className="min-w-0 flex-1"><div className="flex items-center gap-1 font-bold">{p.name}<Verified/></div><div className="text-xs text-brand-muted">{p.city} · {p.match}% connection fit</div></div><Button variant={following?'secondary':'primary'} onClick={()=>toggleFollow(p.id)}>{following?'Following':'Follow back'}</Button></Card>})}</div></div></AppShell>}

function Trust({icon,label}:{icon:ReactNode,label:string}){return <div className="rounded-2xl bg-brand-canvas p-4 text-center"><div className="mx-auto grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-600">{icon}</div><div className="mt-2 text-xs font-semibold">{label}</div></div>}
