import { Bell, ChevronRight, Crown, Eye, HelpCircle, KeyRound, Lock, LogOut, Mail, Moon, ShieldCheck, Smartphone, Trash2, UserRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Button, Card, Field, inputClass } from '../components/ui'

export function SettingsHome(){const nav=useNavigate(); const items=[['Account','Manage your account details',UserRound,'/settings/account'],['Privacy & Safety','Control your privacy and safety',ShieldCheck,'/settings/privacy'],['Notifications','Manage your alerts and updates',Bell,'/settings/notifications'],['Appearance','Customize theme and display',Moon,'#'],['Subscription','View plan and billing details',Crown,'#'],['Support','Help center and contact us',HelpCircle,'#']]; return <AppShell title="Settings" subtitle="Control your account, privacy and experience"><div className="mx-auto max-w-2xl space-y-3">{items.map(([a,b,I,path])=>{const Icon=I as any; return <Card key={a as string}><button onClick={()=>typeof path==='string'&&path!=='#'&&nav(path)} className="flex w-full items-center gap-4 p-4 text-left"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon className="h-5 w-5"/></div><div className="flex-1"><div className="font-bold">{a as string}</div><div className="text-sm text-brand-muted">{b as string}</div></div><ChevronRight className="h-5 w-5 text-slate-400"/></button></Card>})}<Card><button className="flex w-full items-center gap-4 p-4 text-left text-red-600"><div className="grid h-11 w-11 place-items-center rounded-xl bg-red-50"><LogOut className="h-5 w-5"/></div><div><div className="font-bold">Log out</div><div className="text-sm text-red-400">Sign out of your account</div></div></button></Card></div></AppShell>}

export function AccountSettings(){return <AppShell title="Account Settings" subtitle="Email, password, login methods and security"><div className="mx-auto max-w-2xl space-y-5"><Card className="p-5"><h2 className="font-extrabold">Account information</h2><div className="mt-4 space-y-4"><Field label="Email"><div className="relative"><Mail className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input className={`${inputClass} pl-10`} defaultValue="you@example.com"/></div></Field><Field label="Password"><div className="relative"><KeyRound className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input type="password" className={`${inputClass} pl-10`} defaultValue="password123"/></div></Field></div></Card><Card className="p-5"><h2 className="font-extrabold">Connected accounts</h2><div className="mt-4 space-y-3"><Connected name="Google" state="Connected"/><Connected name="GitHub" state="Connected"/><Connected name="Apple" state="Connect"/></div></Card><Card className="p-5"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-600"/><div className="flex-1"><div className="font-bold">Two-factor authentication</div><div className="text-sm text-brand-muted">Add an extra layer of account security</div></div><span className="font-bold text-emerald-600">On</span></div></Card><Button variant="danger" className="w-full"><Trash2 className="h-4 w-4"/>Delete account</Button></div></AppShell>}

export function PrivacySettings(){return <AppShell title="Privacy & Safety" subtitle="You control who can find, message and locate you"><div className="mx-auto max-w-2xl space-y-5"><Card className="p-5"><h2 className="font-extrabold">Privacy controls</h2><div className="mt-4 divide-y divide-brand-line"><Toggle title="Profile visibility" detail="Allow others to find and view your profile" on/><Toggle title="Show city, not exact location" detail="Keep precise location private" on/><Toggle title="Online status" detail="Show when you're online"/></div></Card><Card className="p-5"><h2 className="font-extrabold">Messaging</h2><div className="mt-4 flex items-center justify-between rounded-xl bg-brand-canvas p-4"><div><div className="font-bold">Message permissions</div><div className="text-sm text-brand-muted">Choose who can message you</div></div><span className="font-bold text-brand-600">Everyone</span></div></Card><Card className="p-5"><h2 className="font-extrabold">Safety tools</h2><div className="mt-4 divide-y divide-brand-line"><Row title="Blocked users" detail="12 users"/><Row title="Report center" detail="Review report status"/><Row title="Safety resources" detail="Tips and community guidelines"/></div></Card></div></AppShell>}

export function NotificationSettings(){return <AppShell title="Notification Settings" subtitle="Choose which updates deserve your attention"><div className="mx-auto max-w-2xl space-y-5"><Card className="p-5"><h2 className="font-extrabold">Notification types</h2><div className="mt-4 divide-y divide-brand-line"><Toggle title="Messages" detail="New messages and replies" on/><Toggle title="Connection requests" detail="People who want to connect" on/><Toggle title="Communities" detail="Posts, comments and mentions" on/><Toggle title="Events" detail="Event updates and reminders" on/><Toggle title="Weekly digest" detail="Your weekly community summary" on/></div></Card><Card className="p-5"><h2 className="font-extrabold">Delivery preferences</h2><div className="mt-4 divide-y divide-brand-line"><Toggle title="Push notifications" detail="Instant alerts on this device" on/><Toggle title="Email notifications" detail="Receive selected updates by email" on/></div></Card></div></AppShell>}
function Connected({name,state}:{name:string,state:string}){return <div className="flex items-center justify-between rounded-xl bg-brand-canvas p-4"><div className="font-bold">{name}</div><span className={`text-sm font-bold ${state==='Connected'?'text-emerald-600':'text-brand-600'}`}>{state}</span></div>}
function Toggle({title,detail,on=false}:{title:string,detail:string,on?:boolean}){return <div className="flex items-center gap-4 py-4"><div className="flex-1"><div className="font-bold">{title}</div><div className="text-sm text-brand-muted">{detail}</div></div><div className={`h-7 w-12 rounded-full p-1 ${on?'bg-brand-500':'bg-slate-200'}`}><div className={`h-5 w-5 rounded-full bg-white shadow transition ${on?'ml-auto':''}`}/></div></div>}
function Row({title,detail}:{title:string,detail:string}){return <div className="flex items-center justify-between py-4"><div><div className="font-bold">{title}</div><div className="text-sm text-brand-muted">{detail}</div></div><ChevronRight className="h-5 w-5 text-slate-400"/></div>}
