import { Bell, ChevronRight, Crown, HelpCircle, KeyRound, LogOut, Mail, Moon, ShieldCheck, Trash2, UserRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppShell } from '../components/AppShell'
import { Button, Card, Field, inputClass } from '../components/ui'
import { useMockApp } from '../lib/mockApp'

export function SettingsHome(){const nav=useNavigate(); const {toast}=useMockApp(); const items=[['Account','Manage your account details',UserRound,'/settings/account'],['Privacy & Safety','Control your privacy and safety',ShieldCheck,'/settings/privacy'],['Notifications','Manage your alerts and updates',Bell,'/settings/notifications'],['Appearance','Customize theme and display',Moon,'appearance'],['Subscription','View plan and billing details',Crown,'subscription'],['Support','Help center and contact us',HelpCircle,'support']]; return <AppShell title="Settings" subtitle="Control your account, privacy and experience"><div className="mx-auto max-w-2xl space-y-3">{items.map(([a,b,I,path])=>{const Icon=I as any; return <Card key={a as string}><button onClick={()=>typeof path==='string'&&(path.startsWith('/')?nav(path):toast(`${a} is ready for your production integration`))} className="flex w-full items-center gap-4 p-4 text-left"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon className="h-5 w-5"/></div><div className="flex-1"><div className="font-bold">{a as string}</div><div className="text-sm text-brand-muted">{b as string}</div></div><ChevronRight className="h-5 w-5 text-slate-400"/></button></Card>})}<Card><button onClick={()=>{toast('You have been signed out of the demo');nav('/login')}} className="flex w-full items-center gap-4 p-4 text-left text-red-600"><div className="grid h-11 w-11 place-items-center rounded-xl bg-red-50"><LogOut className="h-5 w-5"/></div><div><div className="font-bold">Log out</div><div className="text-sm text-red-400">Sign out of your account</div></div></button></Card></div></AppShell>}

export function AccountSettings(){const {toast}=useMockApp(); return <AppShell title="Account Settings" subtitle="Email, password, login methods and security"><div className="mx-auto max-w-2xl space-y-5"><Card className="p-5"><h2 className="font-extrabold">Account information</h2><div className="mt-4 space-y-4"><Field label="Email"><div className="relative"><Mail className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input className={`${inputClass} pl-10`} defaultValue="jane@example.com"/></div></Field><Field label="Password"><div className="relative"><KeyRound className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input type="password" className={`${inputClass} pl-10`} defaultValue="password123"/></div></Field></div><Button onClick={()=>toast('Account settings saved')} className="mt-5 w-full">Save account changes</Button></Card><Card className="p-5"><h2 className="font-extrabold">Connected accounts</h2><div className="mt-4 space-y-3"><Connected name="Google" state="Connected"/><Connected name="GitHub" state="Connected"/><Connected name="Apple" state="Connect"/></div></Card><Card className="p-5"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-600"/><div className="flex-1"><div className="font-bold">Two-factor authentication</div><div className="text-sm text-brand-muted">Add an extra layer of account security</div></div><span className="font-bold text-emerald-600">On</span></div></Card><Button variant="danger" onClick={()=>toast('Account deletion requires a secure confirmation in production')} className="w-full"><Trash2 className="h-4 w-4"/>Delete account</Button></div></AppShell>}

export function PrivacySettings(){return <AppShell title="Privacy & Safety" subtitle="You control who can find, message and locate you"><div className="mx-auto max-w-2xl space-y-5"><Card className="p-5"><h2 className="font-extrabold">Privacy controls</h2><div className="mt-4 divide-y divide-brand-line"><Toggle id="profileVisibility" title="Profile visibility" detail="Allow others to find and view your profile"/><Toggle id="cityOnly" title="Show city, not exact location" detail="Keep precise location private"/><Toggle id="onlineStatus" title="Online status" detail="Show when you're online"/></div></Card><Card className="p-5"><h2 className="font-extrabold">Messaging</h2><div className="mt-4 flex items-center justify-between rounded-xl bg-brand-canvas p-4"><div><div className="font-bold">Message permissions</div><div className="text-sm text-brand-muted">Choose who can message you</div></div><span className="font-bold text-brand-600">Everyone</span></div></Card><Card className="p-5"><h2 className="font-extrabold">Safety tools</h2><div className="mt-4 divide-y divide-brand-line"><Row title="Blocked users" detail="12 users"/><Row title="Report center" detail="Review report status"/><Row title="Safety resources" detail="Tips and community guidelines"/></div></Card></div></AppShell>}

export function NotificationSettings(){return <AppShell title="Notification Settings" subtitle="Choose which updates deserve your attention"><div className="mx-auto max-w-2xl space-y-5"><Card className="p-5"><h2 className="font-extrabold">Notification types</h2><div className="mt-4 divide-y divide-brand-line"><Toggle id="messages" title="Messages" detail="New messages and replies"/><Toggle id="connections" title="Connection requests" detail="People who want to connect"/><Toggle id="communities" title="Communities" detail="Posts, comments and mentions"/><Toggle id="events" title="Events" detail="Event updates and reminders"/><Toggle id="digest" title="Weekly digest" detail="Your weekly community summary"/></div></Card><Card className="p-5"><h2 className="font-extrabold">Delivery preferences</h2><div className="mt-4 divide-y divide-brand-line"><Toggle id="push" title="Push notifications" detail="Instant alerts on this device"/><Toggle id="email" title="Email notifications" detail="Receive selected updates by email"/></div></Card></div></AppShell>}
function Connected({name,state}:{name:string,state:string}){return <div className="flex items-center justify-between rounded-xl bg-brand-canvas p-4"><div className="font-bold">{name}</div><span className={`text-sm font-bold ${state==='Connected'?'text-emerald-600':'text-brand-600'}`}>{state}</span></div>}
function Toggle({id,title,detail}:{id:string,title:string,detail:string}){const {settings,toggleSetting}=useMockApp(); const on=Boolean(settings[id]); return <button type="button" onClick={()=>toggleSetting(id)} className="flex w-full items-center gap-4 py-4 text-left"><div className="flex-1"><div className="font-bold">{title}</div><div className="text-sm text-brand-muted">{detail}</div></div><div className={`h-7 w-12 rounded-full p-1 ${on?'bg-brand-500':'bg-slate-200'}`}><div className={`h-5 w-5 rounded-full bg-white shadow transition ${on?'ml-auto':''}`}/></div></button>}
function Row({title,detail}:{title:string,detail:string}){return <div className="flex items-center justify-between py-4"><div><div className="font-bold">{title}</div><div className="text-sm text-brand-muted">{detail}</div></div><ChevronRight className="h-5 w-5 text-slate-400"/></div>}
