import { BadgeCheck, Bookmark, Camera, CheckCircle2, Heart, Image as ImageIcon, MessageCircle, MoreHorizontal, Play, Plus, Search, Send, Share2, Sparkles, Upload, UsersRound, Video } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { AppShell } from '../components/AppShell'
import { Avatar, Button, Card, Chip, Field, inputClass, Verified } from '../components/ui'
import { communities, feedPosts, people } from '../lib/data'

export function Feed(){const [tab,setTab]=useState('For You'); return <AppShell title="Community Feed" subtitle="Content that helps you discover people, communities and local experiences"><div className="mx-auto max-w-3xl"><Stories/><div className="sticky top-[65px] z-10 my-4 flex gap-2 bg-brand-canvas/95 py-2 backdrop-blur">{['For You','Following','Communities'].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-4 py-2 text-sm font-bold ${tab===x?'bg-brand-500 text-white':'border border-brand-line bg-white text-brand-muted'}`}>{x}</button>)}</div><div className="space-y-5">{feedPosts.map(post=><PostCard key={post.id} {...post}/>)}<Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-600"><UsersRound/></div><div className="flex-1"><div className="font-extrabold">Austin Startup Circle</div><div className="text-xs text-brand-muted">Community post · 1h</div></div><Button variant="secondary">Join</Button></div><p className="mt-4 text-sm">Tonight's founder coffee meetup starts at 7 PM. First-timers are welcome. Come curious, leave with at least one new person you know.</p><div className="mt-4 rounded-2xl bg-brand-canvas p-4"><div className="font-bold">Founder Coffee Meetup</div><div className="mt-1 text-xs text-brand-muted">Tonight · 7:00 PM · 3.4 mi away</div></div></Card></div></div></AppShell>}

function Stories(){return <div className="flex gap-4 overflow-x-auto pb-2 no-scrollbar"><Story name="Your Story" add/><Story name="Maya" src={people[0].image}/><Story name="Alex" src={people[1].image}/><Story name="Priya" src={people[2].image}/><Story name="Hikers" src={communities[0].image}/></div>}
function Story({name,src,add=false}:{name:string,src?:string,add?:boolean}){return <button className="shrink-0 text-center"><div className="relative rounded-full bg-gradient-to-tr from-brand-coral via-brand-500 to-brand-sage p-[3px]"><div className="rounded-full bg-white p-[2px]"><Avatar src={src} name={name} size="lg"/></div>{add&&<span className="absolute bottom-0 right-0 grid h-6 w-6 place-items-center rounded-full bg-brand-500 text-white ring-2 ring-white"><Plus className="h-3 w-3"/></span>}</div><div className="mt-1 max-w-16 truncate text-[11px] font-semibold">{name}</div></button>}
function PostCard(post:any){return <Card className="overflow-hidden"><div className="flex items-center gap-3 p-4"><Avatar src={post.avatar} name={post.author}/><div className="flex-1"><div className="flex items-center gap-1 font-bold">{post.author}{post.verified&&<Verified/>}</div><div className="text-xs text-brand-muted">{post.time} · {post.tag}</div></div><MoreHorizontal className="h-5 w-5 text-brand-muted"/></div><p className="px-4 pb-4 text-sm leading-6">{post.text}</p>{post.image&&<img src={post.image} className="max-h-[560px] w-full object-cover"/>}<div className="flex items-center gap-1 border-t border-brand-line p-2"><Action icon={<Heart/>} label={post.likes}/><Action icon={<MessageCircle/>} label={post.comments}/><Action icon={<Bookmark/>} label="Save"/><Action icon={<Share2/>} label="Share"/><Button className="ml-auto py-2">Connect</Button></div></Card>}
function Action({icon,label}:{icon:ReactNode,label:string|number}){return <button className="flex items-center gap-1 rounded-xl px-3 py-2 text-xs font-semibold text-brand-muted hover:bg-brand-canvas">{icon}<span>{label}</span></button>}

export function Videos(){return <AppShell title="Videos" subtitle="Short-form discovery with a path to real connections"><div className="mx-auto max-w-xl space-y-5">{feedPosts.map((p,i)=><Card key={p.id} className="relative aspect-[9/16] max-h-[78vh] overflow-hidden bg-black"><img src={p.image} className="h-full w-full object-cover opacity-85"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/10"/><button className="absolute inset-0 grid place-items-center"><div className="grid h-16 w-16 place-items-center rounded-full bg-white/20 text-white backdrop-blur"><Play className="h-8 w-8 fill-white"/></div></button><div className="absolute bottom-0 left-0 right-0 p-5 text-white"><div className="flex items-center gap-2"><Avatar src={p.avatar} name={p.author}/><div><div className="flex items-center gap-1 font-bold">{p.author}<Verified/></div><div className="text-xs text-white/70">{i===0?'Austin Hikers':'Startup Circle'}</div></div><Button className="ml-auto py-2">Follow</Button></div><p className="mt-4 text-sm">{p.text}</p><div className="mt-4 flex items-center gap-4 text-sm"><span>♡ {p.likes}</span><span>💬 {p.comments}</span><span>↗ Share</span></div><Button variant="secondary" className="mt-4 bg-white/95">View Community</Button></div></Card>)}</div></AppShell>}

export function CreateHub(){return <AppShell title="Create" subtitle="Share something that moves a relationship forward"><div className="mx-auto grid max-w-3xl gap-4 sm:grid-cols-2">{[
  ['Post','Text, image or carousel',ImageIcon],['Story','24-hour photo, video, poll or question',Camera],['Video','Short vertical discovery video',Video],['Event','Bring the community together offline',UsersRound]
].map(([title,desc,I])=>{const Icon=I as any; return <Card key={title as string} className="p-5"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Icon/></div><div className="mt-4 text-lg font-extrabold">{title as string}</div><div className="mt-1 text-sm text-brand-muted">{desc as string}</div><Button className="mt-5 w-full">Create {title as string}</Button></Card>})}</div></AppShell>}

export function CreatePost(){return <AppShell title="Create Post" subtitle="Share something worth responding to"><div className="mx-auto max-w-2xl"><Card className="p-6"><div className="flex items-center gap-3"><Avatar src={people[0].image} name="Jane Doe"/><div><div className="font-bold">Jane Doe</div><select className="mt-1 rounded-lg bg-brand-canvas px-2 py-1 text-xs font-semibold"><option>Public</option><option>Followers</option><option>Connections</option><option>Specific community</option></select></div></div><textarea rows={7} className="mt-5 w-full resize-none border-none text-lg outline-none placeholder:text-slate-400" placeholder="What's on your mind?"/><div className="mt-4 grid grid-cols-4 gap-2"><Media icon={<ImageIcon/>} label="Photo"/><Media icon={<Video/>} label="Video"/><Media icon={<UsersRound/>} label="Community"/><Media icon={<Sparkles/>} label="AI Assist"/></div><Button className="mt-6 w-full"><Send className="h-4 w-4"/>Post</Button></Card></div></AppShell>}
function Media({icon,label}:{icon:ReactNode,label:string}){return <button className="flex flex-col items-center gap-2 rounded-xl bg-brand-canvas p-3 text-xs font-semibold text-brand-muted"><span className="text-brand-500">{icon}</span>{label}</button>}

export function Verification(){return <AppShell title="Get Verified" subtitle="Verification proves account identity. It is separate from Premium."><div className="mx-auto max-w-2xl space-y-5"><Card className="p-6 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-brand-50 text-brand-600"><BadgeCheck className="h-10 w-10"/></div><h2 className="mt-5 text-2xl font-extrabold">Identity Verified</h2><p className="mx-auto mt-2 max-w-md text-sm text-brand-muted">Help people know that the person behind your profile passed identity and liveness verification.</p></Card><Card className="p-6"><div className="space-y-4"><VerifyStep done title="Verify email and phone"/><VerifyStep title="Submit identity document"/><VerifyStep title="Complete selfie / liveness check"/><VerifyStep title="Verification review"/></div><Button className="mt-6 w-full">Start verification</Button><p className="mt-3 text-xs text-brand-muted">Use a specialized identity provider. Avoid storing raw identity documents in your own app unless legally necessary.</p></Card></div></AppShell>}
function VerifyStep({title,done=false}:{title:string,done?:boolean}){return <div className="flex items-center gap-3 rounded-2xl bg-brand-canvas p-4"><div className={`grid h-9 w-9 place-items-center rounded-full ${done?'bg-emerald-100 text-emerald-700':'bg-white text-brand-muted'}`}>{done?<CheckCircle2 className="h-5 w-5"/>:<Upload className="h-4 w-4"/>}</div><div className="font-bold">{title}</div></div>}

export function StoriesViewer(){return <div className="min-h-screen bg-[#0B1020] text-white"><div className="mx-auto flex min-h-screen max-w-lg flex-col"><div className="flex gap-1 p-3">{[1,2,3,4].map((n,i)=><div key={n} className="h-1 flex-1 overflow-hidden rounded-full bg-white/25"><div className={`h-full rounded-full bg-white ${i===0?'w-2/3':'w-0'}`}/></div>)}</div><div className="flex items-center gap-3 px-4 py-2"><Avatar src={people[0].image} name="Maya Patel"/><div className="flex-1"><div className="flex items-center gap-1 font-bold">Maya Patel<Verified/></div><div className="text-xs text-white/60">12m · Austin Hikers</div></div><MoreHorizontal/></div><div className="relative flex-1 overflow-hidden"><img src="https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1000&q=90" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"/><div className="absolute bottom-6 left-5 right-5"><div className="text-2xl font-extrabold">Weekend trail crew 🌿</div><div className="mt-2 text-sm text-white/80">Anyone joining next Saturday?</div><div className="mt-4 grid grid-cols-2 gap-2"><button className="rounded-xl bg-white/20 px-4 py-3 text-sm font-bold backdrop-blur">I'm in</button><button className="rounded-xl bg-white/20 px-4 py-3 text-sm font-bold backdrop-blur">Maybe</button></div></div></div><div className="safe-bottom flex items-center gap-2 p-4"><input className="min-w-0 flex-1 rounded-full border border-white/20 bg-white/10 px-4 py-3 text-sm outline-none placeholder:text-white/50" placeholder="Reply to Maya..."/><button className="grid h-11 w-11 place-items-center rounded-full bg-white text-brand-600"><Send className="h-5 w-5"/></button></div></div></div>}
